name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  deploy:
      runs-on: self-hosted

      steps:
        - name: Fix workspace permissions
          run: sudo chown -R log430:log430 ${{ github.workspace }} && sudo chmod -R u+rwX ${{ github.workspace }}

        - name: Checkout code
          uses: actions/checkout@v4

        - name: Mettre le repo à jour
          shell: bash
          env:
            GITHUB_REPOSITORY: ${{ github.repository }}
          run: |
            set -euo pipefail
            REPO_NAME=$(basename "$GITHUB_REPOSITORY")
            cd ~
            if [ ! -d "$REPO_NAME" ]; then
              git clone https://x-access-token:${{ secrets.TOKEN }}@github.com/${GITHUB_REPOSITORY}.git "$REPO_NAME"
            fi
            cd "$REPO_NAME"
            git fetch --all --prune
            git checkout main
            git pull --ff-only

        - name: Créer fichier .env et déployer l'app
          run: |
            echo "DB_HOST=mysql" > .env
            echo "DB_PORT=3306" >> .env
            echo "DB_NAME=labo05_payments_db" >> .env
            echo "DB_USER=labo05" >> .env
            echo "DB_PASS=labo05" >> .env

            REPO_NAME=$(basename "$GITHUB_REPOSITORY")
            cp .env ~/"$REPO_NAME"/.env

            docker compose down -v
            docker network rm labo05-network || true

            docker network create labo05-network
            docker compose build --no-cache
            docker compose up -d --remove-orphans
            docker image prune -f
            docker container prune -f
            docker volume prune -f
            docker network prune -f
            docker builder prune -af